# Generated by Django 5.2.1 on 2025-05-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirim_chiqim', '0002_remove_kirim_kimdan_uchun_kirim_uchun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valyuta',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
