# Generated by Django 5.2.1 on 2025-05-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kirim_chiqim', '0004_kimdan_alter_kirim_uchun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kirim',
            old_name='uchun',
            new_name='kimdan',
        ),
    ]
