# Generated by Django 5.2.1 on 2025-05-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirim_chiqim', '0005_rename_uchun_kirim_kimdan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqim',
            name='sana',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kirim',
            name='sana',
            field=models.DateField(),
        ),
    ]
