# Generated by Django 5.2.1 on 2025-05-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirim_chiqim', '0006_alter_chiqim_sana_alter_kirim_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valyuta',
            name='short',
            field=models.CharField(max_length=3),
        ),
    ]
