# Generated by Django 5.2.1 on 2025-05-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kirim_chiqim', '0007_alter_valyuta_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiqim',
            name='izoh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kirim',
            name='izoh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
