# Generated by Django 5.1.6 on 2025-05-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='kod_vaqt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='tasdiqla_kod',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='manzil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
