# Generated by Django 5.2.1 on 2025-05-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_profil_kod_vaqt_profil_tasdiqla_kod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='rasm',
            field=models.ImageField(blank=True, default='profil_rasmlari/default.png', null=True, upload_to='profil_rasmlari/'),
        ),
    ]
