# Generated by Django 5.2.1 on 2025-05-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_alter_profil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='tasdiqla_kod',
            field=models.CharField(blank=True, null=True),
        ),
    ]
