# Generated by Django 5.2.1 on 2025-05-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_alter_profil_tasdiqla_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
